name: pemrograman_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  dart_json_mapper: ^2.2.7
  fl_chart: ^1.1.1
  shared_preferences: ^2.2.2
  pdf: ^3.11.3
  printing: ^5.14.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^7.2.0
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_pink_pocket.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_pink_pocket.png"
